config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root to: 'application#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @app_props = { name: "Stranger" }
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/application/index.html.haml
= react_component("App", props: @app_props, prerender: false)

app/views/homes/_form.html.haml
= form_for @home do |f|
  - if @home.errors.any?
    #error_explanation
      %h2= "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"
      %ul
        - @home.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description

  .actions
    = f.submit 'Save'

app/views/homes/edit.html.haml
%h1 Editing home

= render 'form'

= link_to 'Show', @home
\|
= link_to 'Back', homes_path

app/views/homes/index.html.haml
%h1 Listing homes

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @homes.each do |home|
      %tr
        %td= home.name
        %td= home.description

        %td= link_to 'Show', home
        %td= link_to 'Edit', edit_home_path(home)
        %td= link_to 'Destroy', home, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Home', new_home_path

app/views/homes/new.html.haml
%h1 New home

= render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @home.name

= link_to 'Edit', edit_home_path(@home)
\|
= link_to 'Back', homes_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:rel => :stylesheet, :type => :"text/css", :href => "https://fonts.googleapis.com/css?family=Lato|PT+Serif"}
    %title Faume
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield